CREATE TABLE IF NOT EXISTS public.finance_debts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- 'OWE' (I owe money), 'OWED' (Money is owed to me)
    amount_cents BIGINT NOT NULL,
    remaining_cents BIGINT NOT NULL,
    due_date DATE,
    notes TEXT,
    is_archived BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.finance_debts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_debts_all" ON public.finance_debts FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
