-- ==============================================================================
-- SCHEMA COMPLETO PARA EJECUTAR EN SUPABASE SQL EDITOR
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. HISTORIAL DE VERSIONES DE NOTAS
CREATE TABLE IF NOT EXISTS public.note_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL REFERENCES public.notes(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id)
);
ALTER TABLE public.note_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "note_versions_policy" ON public.note_versions;
CREATE POLICY "note_versions_policy" ON public.note_versions FOR ALL USING (
  auth.uid() = created_by OR 
  auth.uid() IN (SELECT user_id FROM public.notes WHERE id = note_id)
) WITH CHECK (
  auth.uid() = created_by OR 
  auth.uid() IN (SELECT user_id FROM public.notes WHERE id = note_id)
);
CREATE INDEX IF NOT EXISTS idx_note_versions_note_id ON public.note_versions(note_id);

-- 2. MODULO DE FINANZAS
CREATE TABLE IF NOT EXISTS public.finance_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'bank',
    balance_cents BIGINT NOT NULL DEFAULT 0,
    credit_limit_cents BIGINT DEFAULT 0,
    cutoff_day INT DEFAULT 15,
    due_day INT DEFAULT 5,
    card_number_last4 TEXT,
    card_color TEXT DEFAULT 'slate',
    currency TEXT NOT NULL DEFAULT 'USD',
    is_archived BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_accounts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_accounts_all" ON public.finance_accounts;
CREATE POLICY "finance_accounts_all" ON public.finance_accounts FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    emoji TEXT DEFAULT '💰',
    color TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_categories_all" ON public.finance_categories;
CREATE POLICY "finance_categories_all" ON public.finance_categories FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES public.finance_accounts(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    amount_cents BIGINT NOT NULL,
    category_id BIGINT REFERENCES public.finance_categories(id) ON DELETE SET NULL,
    date DATE NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_transactions_all" ON public.finance_transactions;
CREATE POLICY "finance_transactions_all" ON public.finance_transactions FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    total_amount_cents BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_budgets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_budgets_all" ON public.finance_budgets;
CREATE POLICY "finance_budgets_all" ON public.finance_budgets FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_budget_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    name TEXT NOT NULL,
    icon TEXT DEFAULT '💰',
    color TEXT DEFAULT '#10b981',
    allocated_cents BIGINT NOT NULL DEFAULT 0,
    category_id BIGINT REFERENCES public.finance_categories(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_budget_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_budget_items_all" ON public.finance_budget_items;
CREATE POLICY "finance_budget_items_all" ON public.finance_budget_items FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_savings_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    target_amount_cents BIGINT NOT NULL,
    current_amount_cents BIGINT NOT NULL DEFAULT 0,
    target_date DATE,
    frequency TEXT DEFAULT 'MONTHLY',
    custom_contribution_cents BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_savings_goals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_savings_goals_all" ON public.finance_savings_goals;
CREATE POLICY "finance_savings_goals_all" ON public.finance_savings_goals FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_savings_contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    goal_id BIGINT REFERENCES public.finance_savings_goals(id) ON DELETE CASCADE,
    amount_cents BIGINT NOT NULL,
    date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_savings_contributions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_savings_contributions_all" ON public.finance_savings_contributions;
CREATE POLICY "finance_savings_contributions_all" ON public.finance_savings_contributions FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_recurring_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES public.finance_accounts(id) ON DELETE SET NULL,
    type TEXT NOT NULL DEFAULT 'EXPENSE',
    amount_cents BIGINT NOT NULL,
    description TEXT,
    frequency TEXT NOT NULL DEFAULT 'monthly',
    start_date DATE NOT NULL,
    next_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_recurring_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_recurring_transactions_all" ON public.finance_recurring_transactions;
CREATE POLICY "finance_recurring_transactions_all" ON public.finance_recurring_transactions FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_shopping_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    is_archived BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_shopping_lists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_shopping_lists_all" ON public.finance_shopping_lists;
CREATE POLICY "finance_shopping_lists_all" ON public.finance_shopping_lists FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_shopping_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    list_id BIGINT REFERENCES public.finance_shopping_lists(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    is_purchased BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_shopping_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_shopping_items_all" ON public.finance_shopping_items;
CREATE POLICY "finance_shopping_items_all" ON public.finance_shopping_items FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_debts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    amount_cents BIGINT NOT NULL,
    remaining_cents BIGINT NOT NULL,
    due_date DATE,
    notes TEXT,
    is_archived BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_debts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_debts_all" ON public.finance_debts;
CREATE POLICY "finance_debts_all" ON public.finance_debts FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_installments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    total_amount_cents BIGINT NOT NULL,
    total_installments INT NOT NULL DEFAULT 1,
    paid_installments INT NOT NULL DEFAULT 0,
    installment_amount_cents BIGINT NOT NULL,
    account_id BIGINT REFERENCES public.finance_accounts(id) ON DELETE SET NULL,
    start_date DATE NOT NULL,
    start_month TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_installments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_installments_all" ON public.finance_installments;
CREATE POLICY "finance_installments_all" ON public.finance_installments FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.finance_security (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    pin_hash TEXT NOT NULL,
    require_on_enter BOOLEAN NOT NULL DEFAULT false,
    require_on_delete BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.finance_security ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "finance_security_all" ON public.finance_security;
CREATE POLICY "finance_security_all" ON public.finance_security FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
