-- ==============================================================================
-- SCHEMA DE PRODUCCIÓN COMPLETO PARA POLLITO LISTA DE TAREAS & WORKSPACE
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABLA DE PERFILES
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    pomodoro_settings JSONB DEFAULT '{}'::jsonb,
    gcal_settings JSONB DEFAULT '{}'::jsonb,
    ui_settings JSONB DEFAULT '{}'::jsonb,
    timezone_offset INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CARPETAS Y NOTAS
CREATE TABLE IF NOT EXISTS public.folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    folder_id BIGINT REFERENCES public.folders(id) ON DELETE SET NULL,
    title TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.quick_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    text TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PROYECTOS E INVITACIONES
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    emoji TEXT DEFAULT '📁',
    color TEXT DEFAULT '#3b82f6',
    is_archived BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'active',
    priority TEXT DEFAULT 'medium',
    start_date DATE,
    target_date DATE,
    lead TEXT,
    kanban_columns JSONB DEFAULT '[]'::jsonb,
    sprints JSONB DEFAULT '[]'::jsonb,
    milestones JSONB DEFAULT '[]'::jsonb,
    docs JSONB DEFAULT '[]'::jsonb,
    inbox JSONB DEFAULT '[]'::jsonb,
    activities JSONB DEFAULT '[]'::jsonb,
    members JSONB DEFAULT '[]'::jsonb,
    template_type TEXT,
    goal_id TEXT,
    channels JSONB DEFAULT '[]'::jsonb,
    chat_messages JSONB DEFAULT '[]'::jsonb,
    polls JSONB DEFAULT '[]'::jsonb,
    huddles JSONB DEFAULT '[]'::jsonb,
    expenses JSONB DEFAULT '[]'::jsonb,
    time_entries JSONB DEFAULT '[]'::jsonb,
    doc_folders JSONB DEFAULT '[]'::jsonb,
    quarterly_priorities JSONB DEFAULT '[]'::jsonb,
    lists JSONB DEFAULT '[]'::jsonb,
    todos JSONB DEFAULT '[]'::jsonb,
    owner_email TEXT,
    owner_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.project_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    project_name TEXT NOT NULL,
    project_emoji TEXT DEFAULT '📁',
    project_color TEXT DEFAULT '#3b82f6',
    inviter_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    inviter_name TEXT,
    inviter_email TEXT,
    sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    sender_email TEXT,
    invitee_email TEXT,
    receiver_email TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TAREAS Y SUBTAREAS
CREATE TABLE IF NOT EXISTS public.todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    priority TEXT DEFAULT 'medium',
    due_date TEXT,
    end_date TEXT,
    start_time TEXT,
    end_time TEXT,
    notes TEXT,
    project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
    gcal_event_id TEXT,
    recurrence JSONB,
    reminder_offset INTEGER,
    reminder_at TIMESTAMPTZ,
    notification_sent BOOLEAN DEFAULT FALSE,
    kanban_column TEXT,
    story_points NUMERIC,
    sprint_id TEXT,
    milestone_id TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    dependencies JSONB DEFAULT '[]'::jsonb,
    comments JSONB DEFAULT '[]'::jsonb,
    attachments JSONB DEFAULT '[]'::jsonb,
    assignee TEXT,
    calendar_provider TEXT,
    calendar_event_link TEXT,
    notion_page_id TEXT,
    notion_url TEXT,
    list_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.subtasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL REFERENCES public.todos(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. HÁBITOS Y REGISTROS
CREATE TABLE IF NOT EXISTS public.habits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    emoji TEXT DEFAULT '🎯',
    frequency JSONB NOT NULL DEFAULT '{"type": "daily"}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.habit_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    habit_id BIGINT NOT NULL REFERENCES public.habits(id) ON DELETE CASCADE,
    completed_at DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_habit_date UNIQUE (user_id, habit_id, completed_at)
);

-- 6. MEDIA, FONDOS Y CONVERSACIONES IA
CREATE TABLE IF NOT EXISTS public.playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    source_id TEXT NOT NULL,
    platform TEXT NOT NULL,
    is_favorite BOOLEAN DEFAULT FALSE,
    thumbnail_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_backgrounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    path TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'image',
    is_favorite BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ai_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL DEFAULT 'Nueva conversación',
    messages JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. ÍNDICES DE RENDIMIENTO
CREATE INDEX IF NOT EXISTS idx_todos_user ON public.todos(user_id);
CREATE INDEX IF NOT EXISTS idx_todos_proj ON public.todos(project_id);
CREATE INDEX IF NOT EXISTS idx_subtasks_todo ON public.subtasks(todo_id);
CREATE INDEX IF NOT EXISTS idx_projects_user ON public.projects(user_id);
CREATE INDEX IF NOT EXISTS idx_notes_user ON public.notes(user_id);
CREATE INDEX IF NOT EXISTS idx_notes_folder ON public.notes(folder_id);
CREATE INDEX IF NOT EXISTS idx_habits_user ON public.habits(user_id);
CREATE INDEX IF NOT EXISTS idx_habit_records_lookup ON public.habit_records(user_id, habit_id, completed_at);
CREATE INDEX IF NOT EXISTS idx_invitations_email ON public.project_invitations(invitee_email, receiver_email);

-- 8. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quick_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subtasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.habit_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.playlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_backgrounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_conversations ENABLE ROW LEVEL SECURITY;

-- 9. POLÍTICAS DE SEGURIDAD
CREATE POLICY "profiles_policy" ON public.profiles FOR ALL USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "folders_policy" ON public.folders FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "notes_policy" ON public.notes FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "quick_notes_policy" ON public.quick_notes FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "habits_policy" ON public.habits FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "habit_records_policy" ON public.habit_records FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "playlists_policy" ON public.playlists FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "user_backgrounds_policy" ON public.user_backgrounds FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "ai_conversations_policy" ON public.ai_conversations FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "projects_policy" ON public.projects FOR ALL USING (
    auth.uid() = user_id 
    OR members @> jsonb_build_array(jsonb_build_object('id', auth.uid()::text))
    OR members @> jsonb_build_array(jsonb_build_object('email', (auth.jwt() ->> 'email')))
) WITH CHECK (
    auth.uid() = user_id 
    OR members @> jsonb_build_array(jsonb_build_object('id', auth.uid()::text))
    OR members @> jsonb_build_array(jsonb_build_object('email', (auth.jwt() ->> 'email')))
);

CREATE POLICY "invitations_policy" ON public.project_invitations FOR ALL USING (
    auth.uid() = inviter_id 
    OR auth.uid() = sender_id 
    OR lower(invitee_email) = lower(auth.jwt() ->> 'email')
    OR lower(receiver_email) = lower(auth.jwt() ->> 'email')
) WITH CHECK (
    auth.uid() = inviter_id 
    OR auth.uid() = sender_id 
    OR lower(invitee_email) = lower(auth.jwt() ->> 'email')
    OR lower(receiver_email) = lower(auth.jwt() ->> 'email')
);

CREATE POLICY "todos_policy" ON public.todos FOR ALL USING (
    auth.uid() = user_id 
    OR (project_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.projects p 
        WHERE p.id = project_id 
        AND (
            p.user_id = auth.uid() 
            OR p.members @> jsonb_build_array(jsonb_build_object('id', auth.uid()::text))
            OR p.members @> jsonb_build_array(jsonb_build_object('email', (auth.jwt() ->> 'email')))
        )
    ))
) WITH CHECK (
    auth.uid() = user_id 
    OR (project_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.projects p 
        WHERE p.id = project_id 
        AND (
            p.user_id = auth.uid() 
            OR p.members @> jsonb_build_array(jsonb_build_object('id', auth.uid()::text))
            OR p.members @> jsonb_build_array(jsonb_build_object('email', (auth.jwt() ->> 'email')))
        )
    ))
);

CREATE POLICY "subtasks_policy" ON public.subtasks FOR ALL USING (
    EXISTS (SELECT 1 FROM public.todos t WHERE t.id = todo_id AND t.user_id = auth.uid())
) WITH CHECK (
    EXISTS (SELECT 1 FROM public.todos t WHERE t.id = todo_id AND t.user_id = auth.uid())
);

-- 10. TRIGGER PARA CREACIÓN AUTOMÁTICA DE PERFIL
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, created_at, updated_at)
  VALUES (new.id, NOW(), NOW())
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 11. HABILITAR REALTIME (SINCRONIZACIÓN EN VIVO)
ALTER PUBLICATION supabase_realtime ADD TABLE public.projects;
ALTER PUBLICATION supabase_realtime ADD TABLE public.todos;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notes;
ALTER PUBLICATION supabase_realtime ADD TABLE public.quick_notes;
ALTER PUBLICATION supabase_realtime ADD TABLE public.habits;
ALTER PUBLICATION supabase_realtime ADD TABLE public.habit_records;
ALTER PUBLICATION supabase_realtime ADD TABLE public.project_invitations;
