CREATE TABLE IF NOT EXISTS public.finance_shopping_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    name TEXT NOT NULL,
    is_archived BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.finance_shopping_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    list_id BIGINT REFERENCES public.finance_shopping_lists(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    is_purchased BOOLEAN NOT NULL DEFAULT false,
    estimated_amount_cents BIGINT,
    actual_amount_cents BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.finance_shopping_lists ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_shopping_lists_all" ON public.finance_shopping_lists FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

ALTER TABLE public.finance_shopping_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_shopping_items_all" ON public.finance_shopping_items FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
