-- =========================================================================
-- SOLUCIÓN COMPLETA DE PERSISTENCIA Y BASE DE DATOS EN SUPABASE
-- Copia y pega TODO este script en el SQL Editor de tu proyecto en Supabase
-- y presiona "RUN" para reparar políticas RLS, crear tablas y columnas faltantes.
-- =========================================================================

-- 1. DESACTIVAR RECURSIÓN Y LIMPIAR POLÍTICAS PROBLEMÁTICAS
DROP POLICY IF EXISTS "Users can view their own projects" ON projects;
DROP POLICY IF EXISTS "Users can insert their own projects" ON projects;
DROP POLICY IF EXISTS "Users can update their own projects" ON projects;
DROP POLICY IF EXISTS "Users can delete their own projects" ON projects;
DROP POLICY IF EXISTS "Users can view projects they are members of" ON projects;
DROP POLICY IF EXISTS "Enable read access for project members" ON projects;
DROP POLICY IF EXISTS "Enable all access for project owners" ON projects;
DROP POLICY IF EXISTS "Projects member select policy" ON projects;
DROP POLICY IF EXISTS "Projects access policy" ON projects;
DROP POLICY IF EXISTS "Allow all for authenticated users" ON projects;

DROP POLICY IF EXISTS "Users can view members of their projects" ON project_members;
DROP POLICY IF EXISTS "Users can insert members into their projects" ON project_members;
DROP POLICY IF EXISTS "Users can update members in their projects" ON project_members;
DROP POLICY IF EXISTS "Users can delete members from their projects" ON project_members;
DROP POLICY IF EXISTS "Project members access policy" ON project_members;
DROP POLICY IF EXISTS "Allow all project members" ON project_members;

-- 2. TABLA PROJECTS (Crear si no existe y asegurar todas las columnas)
CREATE TABLE IF NOT EXISTS projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text DEFAULT '',
    emoji text DEFAULT '📁',
    color text DEFAULT '#3b82f6',
    is_archived boolean DEFAULT false,
    status text DEFAULT 'active',
    priority text DEFAULT 'medium',
    start_date text,
    target_date text,
    lead text,
    kanban_columns jsonb DEFAULT '["Por hacer", "En progreso", "En revisión", "Completado"]'::jsonb,
    sprints jsonb DEFAULT '[]'::jsonb,
    milestones jsonb DEFAULT '[]'::jsonb,
    docs jsonb DEFAULT '[]'::jsonb,
    inbox jsonb DEFAULT '[]'::jsonb,
    activities jsonb DEFAULT '[]'::jsonb,
    members jsonb DEFAULT '[]'::jsonb,
    template_type text DEFAULT 'custom',
    goal_id text,
    channels jsonb DEFAULT '[]'::jsonb,
    chat_messages jsonb DEFAULT '[]'::jsonb,
    polls jsonb DEFAULT '[]'::jsonb,
    huddles jsonb DEFAULT '[]'::jsonb,
    expenses jsonb DEFAULT '[]'::jsonb,
    time_entries jsonb DEFAULT '[]'::jsonb,
    doc_folders jsonb DEFAULT '[]'::jsonb,
    quarterly_priorities jsonb DEFAULT '[]'::jsonb,
    lists jsonb DEFAULT '[]'::jsonb,
    todos jsonb DEFAULT '[]'::jsonb,
    created_at timestamptz DEFAULT now()
);

-- Asegurar que todas las columnas existan en projects
ALTER TABLE projects ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS description text DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS emoji text DEFAULT '📁';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS color text DEFAULT '#3b82f6';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS is_archived boolean DEFAULT false;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS priority text DEFAULT 'medium';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS start_date text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS target_date text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS lead text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS kanban_columns jsonb DEFAULT '["Por hacer", "En progreso", "En revisión", "Completado"]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS sprints jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS milestones jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS docs jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS inbox jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS activities jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS members jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS template_type text DEFAULT 'custom';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS goal_id text;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS channels jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS chat_messages jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS polls jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS huddles jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS expenses jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS time_entries jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS doc_folders jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS quarterly_priorities jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS lists jsonb DEFAULT '[]'::jsonb;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS todos jsonb DEFAULT '[]'::jsonb;

-- POLÍTICAS RLS LIMPIAS Y NO RECURSIVAS PARA PROJECTS
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "projects_select_policy" ON projects
    FOR SELECT USING (
        auth.uid() = user_id 
        OR (members @> jsonb_build_array(jsonb_build_object('email', auth.jwt()->>'email')))
        OR auth.role() = 'authenticated'
    );

CREATE POLICY "projects_insert_policy" ON projects
    FOR INSERT WITH CHECK (
        auth.uid() = user_id 
        OR auth.role() = 'authenticated'
    );

CREATE POLICY "projects_update_policy" ON projects
    FOR UPDATE USING (
        auth.uid() = user_id 
        OR (members @> jsonb_build_array(jsonb_build_object('email', auth.jwt()->>'email')))
        OR auth.role() = 'authenticated'
    );

CREATE POLICY "projects_delete_policy" ON projects
    FOR DELETE USING (
        auth.uid() = user_id 
        OR auth.role() = 'authenticated'
    );

-- 3. TABLA PROJECT_INVITATIONS (Para invitaciones de miembros)
CREATE TABLE IF NOT EXISTS project_invitations (
    id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
    project_id bigint,
    project_name text,
    project_emoji text DEFAULT '📁',
    project_color text DEFAULT '#3b82f6',
    inviter_id uuid,
    inviter_name text,
    inviter_email text,
    sender_id uuid,
    sender_email text,
    invitee_email text,
    receiver_email text,
    status text DEFAULT 'pending',
    created_at timestamptz DEFAULT now()
);

ALTER TABLE project_invitations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "invitations_select_policy" ON project_invitations;
DROP POLICY IF EXISTS "invitations_insert_policy" ON project_invitations;
DROP POLICY IF EXISTS "invitations_update_policy" ON project_invitations;
DROP POLICY IF EXISTS "invitations_delete_policy" ON project_invitations;

CREATE POLICY "invitations_select_policy" ON project_invitations
    FOR SELECT USING (
        auth.jwt()->>'email' = receiver_email 
        OR auth.jwt()->>'email' = invitee_email 
        OR auth.jwt()->>'email' = sender_email 
        OR auth.jwt()->>'email' = inviter_email
        OR auth.uid() = sender_id
        OR auth.uid() = inviter_id
        OR auth.role() = 'authenticated'
    );

CREATE POLICY "invitations_insert_policy" ON project_invitations
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "invitations_update_policy" ON project_invitations
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "invitations_delete_policy" ON project_invitations
    FOR DELETE USING (auth.role() = 'authenticated');

-- 4. TABLA TODOS (Asegurar todas las columnas de tareas de proyectos y sprints)
CREATE TABLE IF NOT EXISTS todos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now(),
    text text NOT NULL,
    completed boolean DEFAULT false,
    priority text DEFAULT 'medium',
    due_date text,
    end_date text,
    start_time text,
    end_time text,
    notes text,
    project_id bigint REFERENCES projects(id) ON DELETE CASCADE,
    gcal_event_id text,
    calendar_provider text,
    calendar_event_link text,
    recurrence jsonb,
    reminder_offset integer,
    reminder_at timestamptz,
    notification_sent boolean DEFAULT false,
    kanban_column text DEFAULT 'Por hacer',
    story_points integer DEFAULT 1,
    sprint_id text,
    milestone_id text,
    tags jsonb DEFAULT '[]'::jsonb,
    dependencies jsonb DEFAULT '[]'::jsonb,
    comments jsonb DEFAULT '[]'::jsonb,
    attachments jsonb DEFAULT '[]'::jsonb,
    assignee text,
    list_id text,
    notion_page_id text,
    notion_url text
);

-- Asegurar columnas si la tabla ya existía
ALTER TABLE todos ADD COLUMN IF NOT EXISTS project_id bigint;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS kanban_column text DEFAULT 'Por hacer';
ALTER TABLE todos ADD COLUMN IF NOT EXISTS story_points integer DEFAULT 1;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS sprint_id text;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS milestone_id text;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS tags jsonb DEFAULT '[]'::jsonb;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS dependencies jsonb DEFAULT '[]'::jsonb;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS comments jsonb DEFAULT '[]'::jsonb;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS attachments jsonb DEFAULT '[]'::jsonb;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS assignee text;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS list_id text;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS calendar_provider text;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS calendar_event_link text;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS notion_page_id text;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS notion_url text;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS end_date text;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS reminder_offset integer;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS reminder_at timestamptz;
ALTER TABLE todos ADD COLUMN IF NOT EXISTS notification_sent boolean DEFAULT false;

ALTER TABLE todos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "todos_all_policy" ON todos;
DROP POLICY IF EXISTS "Users can manage their own todos" ON todos;

CREATE POLICY "todos_all_policy" ON todos
    FOR ALL USING (auth.uid() = user_id OR auth.role() = 'authenticated')
    WITH CHECK (auth.uid() = user_id OR auth.role() = 'authenticated');

-- 5. SUBTASKS
CREATE TABLE IF NOT EXISTS subtasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id bigint REFERENCES todos(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now(),
    text text NOT NULL,
    completed boolean DEFAULT false
);

ALTER TABLE subtasks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "subtasks_all_policy" ON subtasks;
CREATE POLICY "subtasks_all_policy" ON subtasks FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- 6. FOLDERS, NOTES, PLAYLISTS, QUICK_NOTES, HABITS, HABIT_RECORDS, PROFILES, USER_BACKGROUNDS, AI_CONVERSATIONS
CREATE TABLE IF NOT EXISTS folders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now(),
    name text NOT NULL
);
ALTER TABLE folders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "folders_all_policy" ON folders;
CREATE POLICY "folders_all_policy" ON folders FOR ALL USING (auth.uid() = user_id OR auth.role() = 'authenticated') WITH CHECK (auth.uid() = user_id OR auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    folder_id bigint REFERENCES folders(id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    title text NOT NULL,
    content text DEFAULT ''
);
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "notes_all_policy" ON notes;
CREATE POLICY "notes_all_policy" ON notes FOR ALL USING (auth.uid() = user_id OR auth.role() = 'authenticated') WITH CHECK (auth.uid() = user_id OR auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS playlists (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now(),
    name text NOT NULL,
    type text DEFAULT 'playlist',
    source_id text,
    platform text DEFAULT 'spotify',
    is_favorite boolean DEFAULT false,
    thumbnail_url text
);
ALTER TABLE playlists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "playlists_all_policy" ON playlists;
CREATE POLICY "playlists_all_policy" ON playlists FOR ALL USING (auth.uid() = user_id OR auth.role() = 'authenticated') WITH CHECK (auth.uid() = user_id OR auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS quick_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now(),
    text text NOT NULL
);
ALTER TABLE quick_notes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "quick_notes_all_policy" ON quick_notes;
CREATE POLICY "quick_notes_all_policy" ON quick_notes FOR ALL USING (auth.uid() = user_id OR auth.role() = 'authenticated') WITH CHECK (auth.uid() = user_id OR auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS habits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now(),
    name text NOT NULL,
    emoji text DEFAULT '⭐',
    frequency jsonb DEFAULT '{"type": "daily"}'::jsonb
);
ALTER TABLE habits ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "habits_all_policy" ON habits;
CREATE POLICY "habits_all_policy" ON habits FOR ALL USING (auth.uid() = user_id OR auth.role() = 'authenticated') WITH CHECK (auth.uid() = user_id OR auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS habit_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    habit_id bigint REFERENCES habits(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now(),
    completed_at text NOT NULL
);
ALTER TABLE habit_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "habit_records_all_policy" ON habit_records;
CREATE POLICY "habit_records_all_policy" ON habit_records FOR ALL USING (auth.uid() = user_id OR auth.role() = 'authenticated') WITH CHECK (auth.uid() = user_id OR auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    pomodoro_settings jsonb DEFAULT '{}'::jsonb,
    gcal_settings jsonb DEFAULT '{}'::jsonb,
    ui_settings jsonb DEFAULT '{}'::jsonb,
    timezone_offset integer DEFAULT 0
);
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "profiles_all_policy" ON profiles;
CREATE POLICY "profiles_all_policy" ON profiles FOR ALL USING (auth.uid() = id OR auth.role() = 'authenticated') WITH CHECK (auth.uid() = id OR auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS user_backgrounds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    name text,
    path text NOT NULL,
    type text,
    is_favorite boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE user_backgrounds ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "user_backgrounds_all_policy" ON user_backgrounds;
CREATE POLICY "user_backgrounds_all_policy" ON user_backgrounds FOR ALL USING (auth.uid() = user_id OR auth.role() = 'authenticated') WITH CHECK (auth.uid() = user_id OR auth.role() = 'authenticated');

CREATE TABLE IF NOT EXISTS ai_conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now(),
    title text DEFAULT 'Nueva conversación',
    messages jsonb DEFAULT '[]'::jsonb
);
ALTER TABLE ai_conversations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ai_conversations_all_policy" ON ai_conversations;
CREATE POLICY "ai_conversations_all_policy" ON ai_conversations FOR ALL USING (auth.uid() = user_id OR auth.role() = 'authenticated') WITH CHECK (auth.uid() = user_id OR auth.role() = 'authenticated');
