-- Finance Module Schema for Supabase

-- 1. Accounts
CREATE TABLE IF NOT EXISTS public.finance_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- 'bank', 'cash', 'savings', 'wallet', 'investment'
    balance_cents BIGINT NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'USD',
    is_archived BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Categories
CREATE TABLE IF NOT EXISTS public.finance_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    name TEXT NOT NULL,
    emoji TEXT,
    color TEXT,
    parent_id BIGINT REFERENCES public.finance_categories(id) ON DELETE SET NULL,
    is_archived BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Transactions
CREATE TABLE IF NOT EXISTS public.finance_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    account_id BIGINT REFERENCES public.finance_accounts(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- 'EXPENSE', 'INCOME', 'TRANSFER_OUT', 'TRANSFER_IN', 'REFUND'
    amount_cents BIGINT NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    category_id BIGINT REFERENCES public.finance_categories(id) ON DELETE SET NULL,
    date DATE NOT NULL,
    time TIME WITHOUT TIME ZONE,
    description TEXT,
    notes TEXT,
    merchant TEXT,
    payment_method TEXT,
    related_transfer_id BIGINT REFERENCES public.finance_transactions(id) ON DELETE SET NULL,
    tags TEXT[] DEFAULT '{}',
    is_recurring_instance BOOLEAN NOT NULL DEFAULT false,
    recurring_transaction_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Recurring Transactions
CREATE TABLE IF NOT EXISTS public.finance_recurring_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    account_id BIGINT REFERENCES public.finance_accounts(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    amount_cents BIGINT NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    category_id BIGINT REFERENCES public.finance_categories(id) ON DELETE SET NULL,
    description TEXT,
    frequency TEXT NOT NULL, -- 'weekly', 'monthly', 'yearly', 'custom'
    frequency_interval INTEGER DEFAULT 1,
    start_date DATE NOT NULL,
    next_date DATE NOT NULL,
    end_date DATE,
    auto_create BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.finance_transactions ADD CONSTRAINT fk_recurring_id FOREIGN KEY (recurring_transaction_id) REFERENCES public.finance_recurring_transactions(id) ON DELETE SET NULL;


-- 5. Budgets
CREATE TABLE IF NOT EXISTS public.finance_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    month TEXT NOT NULL, -- 'YYYY-MM'
    total_amount_cents BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Category Budgets
CREATE TABLE IF NOT EXISTS public.finance_category_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    budget_id BIGINT REFERENCES public.finance_budgets(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES public.finance_categories(id) ON DELETE CASCADE,
    amount_cents BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Savings Goals
CREATE TABLE IF NOT EXISTS public.finance_savings_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    name TEXT NOT NULL,
    target_amount_cents BIGINT NOT NULL,
    current_amount_cents BIGINT NOT NULL DEFAULT 0,
    target_date DATE,
    account_id BIGINT REFERENCES public.finance_accounts(id) ON DELETE SET NULL,
    notes TEXT,
    is_completed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Savings Contributions
CREATE TABLE IF NOT EXISTS public.finance_savings_contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    goal_id BIGINT REFERENCES public.finance_savings_goals(id) ON DELETE CASCADE,
    amount_cents BIGINT NOT NULL,
    date DATE NOT NULL,
    transaction_id BIGINT REFERENCES public.finance_transactions(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- Indexes
CREATE INDEX IF NOT EXISTS idx_finance_accounts_user ON public.finance_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_finance_categories_user ON public.finance_categories(user_id);
CREATE INDEX IF NOT EXISTS idx_finance_transactions_user ON public.finance_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_finance_transactions_date ON public.finance_transactions(date);
CREATE INDEX IF NOT EXISTS idx_finance_transactions_account ON public.finance_transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_finance_transactions_category ON public.finance_transactions(category_id);


-- RLS Policies
ALTER TABLE public.finance_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_accounts_all_policy" ON public.finance_accounts FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

ALTER TABLE public.finance_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_categories_all_policy" ON public.finance_categories FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

ALTER TABLE public.finance_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_transactions_all_policy" ON public.finance_transactions FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

ALTER TABLE public.finance_recurring_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_recurring_transactions_all_policy" ON public.finance_recurring_transactions FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

ALTER TABLE public.finance_budgets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_budgets_all_policy" ON public.finance_budgets FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

ALTER TABLE public.finance_category_budgets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_category_budgets_all_policy" ON public.finance_category_budgets FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

ALTER TABLE public.finance_savings_goals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_savings_goals_all_policy" ON public.finance_savings_goals FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

ALTER TABLE public.finance_savings_contributions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_savings_contributions_all_policy" ON public.finance_savings_contributions FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
